name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: my_password  # Only set this for root user
          MYSQL_DATABASE: test_db           # Your database name
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=10s --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load environment variables from .env file
        run: |
          export $(cat .env | xargs)

      - name: Wait for MySQL to be ready
        run: |
          until mysql -h 127.0.0.1 -u root -pmy_password -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Grant permissions to root user and create database
        run: |
          mysql -h 127.0.0.1 -u root -pmy_password -e "CREATE DATABASE IF NOT EXISTS test_db;"
          mysql -h 127.0.0.1 -u root -pmy_password -e "FLUSH PRIVILEGES;"

      - name: Run Django migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
