name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-testcases:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306  # MySQL container uses port 3306 inside the container
        options: >-
          --env MYSQL_ROOT_PASSWORD=Cheruku@0627
          --env MYSQL_DATABASE=test_rateratepro
          -e GITHUB_ACTIONS=true
          -e CI=true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Set up MySQL client
        run: sudo apt-get install mysql-client

      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysql -h 127.0.0.1 -P 3307 -u root -pCheruku@0627 -e "SHOW DATABASES;"; do  # Change port to 3307
            echo "Waiting for MySQL..."
            sleep 5
          done
          echo "MySQL is ready!"

      - name: Run tests
        run: |
          python manage.py test  # Run Django tests
