name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-testcases:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306  # MySQL container uses port 3306 inside the container
        options: >-
          --env MYSQL_ROOT_PASSWORD=testpassword 
          --env MYSQL_DATABASE=test_rateratepro
          -e GITHUB_ACTIONS=true
          -e CI=true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies

      - name: Set up MySQL client
        run: sudo apt-get install mysql-client

      - name: Wait for MySQL to start
        run: |
          echo "Waiting for MySQL to be ready..."
          until mysqladmin -h ${{vars.MYSQL_HOST}} -P ${{vars.MYSQL_PORT}} -u ${{vars.MYSQL_USER}} -p${{secrets.MYSQL_ROOT_PASSWORD}} ping --silent; do
              echo "Waiting for MySQL..."
              sleep 10
          done
          echo "MySQL is ready!"

      - name: Run tests
        env:
          DATABASE_HOST: ${{vars.MYSQL_HOST}} # Point to the MySQL service
          DATABASE_PORT: ${{vars.MYSQL_PORT}}        # Use the correct MySQL port
          DATABASE_NAME: test_rateratepro
          DATABASE_USER: ${{vars.MYSQL_USER}}
          DATABASE_PASSWORD: ${{secrets.MYSQL_ROOT_PASSWORD}}
        run: |
          python manage.py test  # Run Django tests
      
      - name: Send success email
        if: success()  # This step will run only if the workflow is successful
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{vars.SMTP_USERNAME}}  
          password: ${{secrets.SMTP_PASSWORD}}
          subject: "GitHub Actions Workflow Succeeded"
          body: |
            The API test cases have been successfully executed.
            All tests passed. You can review the details in the GitHub Actions logs.
          to: |
            munazzahrizwan.rakhangi@slu.edu
          from: Vamsi Cheruku vamsi.cheruku@slu.edu