name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test-cases:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: Cheruku@0627
          MYSQL_DATABASE: test_rateratepro
          MYSQL_USER: root
          MYSQL_PASSWORD: Cheruku@0627
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..10}; do
          mysqladmin ping -h 127.0.0.1 --user=root --password=rootpassword --silent && break
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
    - name: Run migrations
      run: |
        python manage.py migrate
    - name: Run tests
      run: |
        python manage.py test
