name: Django CI

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: test_rateratepro
          MYSQL_USER: root
          MYSQL_PASSWORD: Cheruku@0627
          MYSQL_ROOT_PASSWORD: Cheruku@0627
        ports:
          - "3306:3306"
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=Cheruku@0627"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: mysql://root:Cheruku@0627@127.0.0.1:3306/test_db
      DEBUG: 'False'
      DJANGO_SETTINGS_MODULE: RateRatePro.settings

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 -u root --password=root_password; do
            sleep 5
          done

      - name: Run migrations
        run: |
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test
